stages:
  - build
  - deploy

variables:
  CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_NAME .
    - docker push $CONTAINER_NAME

deploy:
  stage: deploy
  script:
    - curl -X POST -data=""  https://deliverous.com/api/v1/trigger/$DELIVEROUS_TRIGGER
  only:
    - master

